### ISSUE TITLE
Enhancement request: The displayed time to be localized depending on the browser’s time zone

### ISSUE THREAD

**Issue by achuchev** [Axway/ats-testexplorer#1]
In our test environment, we have boxes which are placed in different locations i.e different time zones. For example, the MUT has one time zone, the test executor has different time zone, the Test Explorer has different time zone, and the QA’s browser has another time zone. 

Currently all events are reported in UTC, but on the Test Explorer UI it is displayed depending on the time zone of the Test Explorer box. This leads to hard troubleshooting of issues, as you need to know the time zone of the TE to be able to calculate the correct time.

The proposal is to display the event time depending on the time zone of the browser.

**Comment by dslaveykov** [comment]
Enhancement has been implemented. You can check it out and provide feedback.

**Comment by achuchev** [comment]
Excellent job. The enhancement works very well.
